weaponMapping = {
    #Missles & Torps
    "MRCK_S10_RSI_Polaris_Torpedo_rt": "S10 Polaris Torpedo",
    "MRCK_S10_RSI_Polaris_Torpedo_rb": "S10 Polaris Torpedo",
    "MRCK_S10_RSI_Polaris_Torpedo_lb": "S10 Polaris Torpedo",
    "MRCK_S10_RSI_Polaris_Torpedo_lt": "S10 Polaris Torpedo",
    "MRCK_S03_AEGS_Sabre_Firebird": "Thunderbolt III",
    "MRCK_S03_BEHR_Quad_S01": "Pioneer I",
    "MRCK_S09_AEGS_Retaliator_Fore": "Argos IX",
    "MRCK_S04_BEHR_Octo_S01": "Taskforce I",
    "BMBRCK_S03_BEHR_Single_S03": "Thunder Ball",
    "BMBRCK_CRUS_Spirit_A1":"A1 Bomb",
    "BMBRCK_CRUS_STARL_Left":"A2 Bomb",
    "BMBRCK_CRUS_STARL_Right":"A2 Bomb",
    #Ship weapons
    "RSI_Bespoke_BallisticCannon_A": "S6 Polaris Ballistic Cannon",
    "BEHR_LaserCannon_SF7E_S7":"Ion Cannon",
    "KLWE_MassDriver_S10": "Tungsten Refrigerator",
    "HRST_LaserBeam_Bespoke": "The SUN",
    "KLWE_LaserRepeater_S1": "CF-117 Bulldog",
    "KLWE_LaserRepeater_S2": "CF-227 Badger",
    "KLWE_LaserRepeater_S3": "CF-337 Panther",
    "KLWE_LaserRepeater_S4": "CF-447 Rhino",
    "KLWE_LaserRepeater_S5": "CF-557 Galdereen",
    "KLWE_LaserRepeater_S6": "CF-667 Mammoth",
    "NONE_LaserRepeater_S1": "Ardor-1",
    "NONE_LaserRepeater_S2": "Ardor-2",
    "NONE_LaserRepeater_S3": "Ardor-3",
    "HRST_LaserRepeater_S1": "Attrition-1",
    "HRST_LaserRepeater_S2": "Attrition-2",
    "HRST_LaserRepeater_S3": "Attrition-3",
    "HRST_LaserRepeater_S4": "Attrition-4",
    "HRST_LaserRepeater_S5": "Attrition-5",
    "HRST_LaserRepeater_S6": "Attrition-6",
    "MXOX_NeutronRepeater_S1": "NDB-26",
    "MXOX_NeutronRepeater_S2": "NDB-28",
    "MXOX_NeutronRepeater_S3": "NDB-30",
    "KRON_LaserCannon_S3":"FL-33 Cannon",
    "AMRS_LaserCannon_S1": "Omnisky III",
    "AMRS_LaserCannon_S2": "Omnisky VI",
    "AMRS_LaserCannon_S3": "Omnisky IX",
    "AMRS_LaserCannon_S4": "Omnisky XII",
    "AMRS_LaserCannon_S5": "Omnisky XV",
    "AMRS_LaserCannon_S6": "Omnisky XVII",
    "BEHR_BallisticGatling_S4": "AD4B",
    "BEHR_BallisticGatling_S5": "AD5B",
    "BEHR_BallisticGatling_S6": "AD6B",
    "BEHR_LaserCannon_S4": "M6A Cannon",
    "GATS_BallisticGatling_S3": "Mantis GT-220 Gatling",
    "APAR_MassDriver_S2": "Strife Mass Driver",
    "BEHR_BallisticGatling_Hornet_Bespoke":"MiniGun Go Burrr",
    "APAR_BallisticGatling_S4":"MinigGun Go Burrr",
    "VNCL_PlasmaCannon_S3":"WARLORD Cannon",
    "VNCL_LaserCannon_S2":"WASP Repeater",
    "GATS_BallisticCannon_S3 ":"Tarantula GT-870 Mark 3 Cannon",
    #FPS weapons
    #Melee
    "none_melee_01": "Dropped the Soap",
    "utfl_melee_01_red01_gungame":"I WON GUN GAME",
    "utfl_melee_01_gungame":"FSK-8 Combat Knife",
    #C54 SMG
    "gmni_smg_ballistic_01": "C54 SMG",
    "gmni_smg_ballistic_01_Luminalia": "C54 Luminalia",
    "gmni_smg_ballistic_01_green_grey01": "C54 Luckbringer",
    "gmni_smg_ballistic_01_Justified": "C54 Justified",
    "gmni_smg_ballistic_01_Scorched": "C54 Scorched",
    "gmni_smg_ballistic_01_Starchaser": "C54 Starchaser",
    #P8-SC
    "behr_smg_ballistic_01": "P8-SC",
    "behr_smg_ballistic_01_white02": "P8-SC Boneyard",
    "behr_smg_ballistic_01_tan01": "P8-SC Desert Shadow",
    "behr_smg_ballistic_01_gold01": "P8-SC Executive",
    "behr_smg_ballistic_01_black01": "P8-SC Midnight",
    "behr_smg_ballistic_01_black02": "P8-SC Nightstalker",
    "behr_smg_ballistic_01_iae2201": "P8-SC Red Alert",
    "behr_smg_ballistic_01_white01": "P8-SC Stormfall",
    "behr_smg_ballistic_01_green01": "P8-SC  Warhawk",
    # P8-AR
    "behr_rifle_ballistic_02_civilian": "P8-AR",
    "behr_rifle_ballistic_01_spc_01": "P8-AR",
    "behr_rifle_ballistic_02_civilian_black01": "P8-AR",
    "behr_rifle_ballistic_02_military": "P8-AR Military",
    "behr_rifle_ballistic_02_P8SC": "P8-AR P8SC",
    "behr_rifle_ballistic_02_Scorched": "P8-AR Scorched",
    "behr_rifle_ballistic_02_Stalker": "P8-AR Stalker",
    "behr_rifle_ballistic_02_Warlord": "P8-AR Warlord",
    "behr_rifle_ballistic_02_civilian_blue01":"P8-AR CitizenCon 2954",
    # P4-AR
    "behr_rifle_ballistic_01": "P4-AR",
    "behr_rifle_ballistic_01_black02": "P4-AR Nightstalker",
    "behr_rifle_ballistic_01_green01": "P4-AR Woodland",
    "behr_rifle_ballistic_01_red01": "P4-AR Red Alert",
    "behr_rifle_ballistic_01_white01": "P4-AR Arctic",
    "behr_rifle_ballistic_01_yellow01": "P4-AR Desert Strike",
    #Karna Rifle
    "ksar_rifle_energy_01": "Karna Rifle",
    "ksar_rifle_energy_01_pink_red01": "Hello Kitty Karna",
    "ksar_rifle_energy_01_red01": "Karna Brimstone Rifle",
    "ksar_rifle_energy_01_black01": "Karna Blackout Rifle",
    "ksar_rifle_energy_01_blue_gold":"Karna Valor Rifle",
    "ksar_rifle_energy_01_blue_gold_spc_01":"Karna Valor Rifle",
    "ksar_rifle_energy_01_iae2023":"Karna Ascension Rifle",
    "ksar_rifle_energy_01_firerats01_spc": "Karna Scorched Rifle",
    "ksar_rifle_energy_01_red_green01": "Karna Christmas Rifle",
    # FS-9 LMG
    "behr_lmg_ballistic_01": "FS-9",
    "behr_lmg_ballistic_01_yellow_grey01": "FS-9 Yellow",
    "behr_lmg_ballistic_01_green01": "FS-9 Woodland",
    "behr_lmg_ballistic_01_black01": "FS-9 Nightstalker",
    "behr_lmg_ballistic_01_red01": "FS-9 Inferno",
    "behr_lmg_ballistic_01_blue01": "FS-9 Oceanic",
    "behr_lmg_ballistic_01_xenothreat01":"FS-9 Stoneface",
    #Demeco LMG
    "klwe_lmg_energy_01": "Demeco LMG",
    "klwe_lmg_energy_01_purple_blue01":"Demeco Purple LMG",
    "klwe_lmg_energy_01_iae2201":"Demeco IAE LMG",
    #F55 LMG
    "gmni_lmg_ballistic_01_blue_gold": "F55 LMG",
    "gmni_lmg_ballistic_01": "F55 LMG",
    "gmni_lmg_ballistic_01_green_red01": "Christmas F55 LMG",
    "gmni_lmg_ballistic_01_firerats01":"Scorched F55 LMG",
    #Devastator Shotgun
    "ksar_shotgun_energy_01_gold01": "Devastator Executive Shotgun",
    "ksar_shotgun_energy_01":"Devastator Shotgun",
    #S71 Rifle
    "gmni_rifle_ballistic_01": "S71 Rifle",
    "gmni_rifle_ballistic_01_firerats01": "S71 Bullseye",
    #Pistols
    "gmni_pistol_ballistic_01":"LH86 Pistol",
    "behr_pistol_ballistic_01":"S-38 Pistol",
    "ksar_pistol_ballistic_01":"Coda Revolver",
    "hdgw_pistol_ballistic_01":"Salvo Frag Pistol",
    "hdgw_pistol_ballistic_01_engraved01": "Salvo Saeed Frag Pistol",
    "klwe_pistol_energy_01": "Arclight pistol",
    "lbco_pistol_energy_01":"Yurabrev Pistol",
    #Lazer Weapons
    "volt_smg_energy_01":"Quartz Energy SMG",
    "volt_smg_energy_01_tint02":"Quartz Energy SMG",
    "volt_smg_energy_01_store02":"Quartz Clawed Steel Energy SMG",
    "volt_rifle_energy_01": "Volt Parallax Rifle",
    "volt_rifle_energy_01_tint02": "Volt Parallax Rifle",
    "volt_rifle_energy_01_camo01": "Volt Parallax Shock Trooper Rifle",
    "volt_rifle_energy_01_black_gold01":"Volt Parallax Downburst Rifle",
    "volt_shotgun_energy_01_tint01": "Volt Parallax Shotgun",
    "volt_shotgun_energy_01": "Volt Parallax Shotgun",
    "volt_shotgun_energy_01_tint03": "Volt Parallax Shotgun",
    #BR-2
    "behr_shotgun_ballistic_01":"BR-2 Shotgun",
    #Gallant Rifle
    "klwe_rifle_energy_01":"Gallant Rifle",
    "klwe_rifle_energy_01_green01":"Gallant Scrubland",
    "klwe_rifle_energy_01_black01": "Gallant Midnight",
    #Lumin V
    "klwe_smg_energy_01_blue_gold":"LuminV Invictus SMG",
    "klwe_smg_energy_01":"Lumin V",
    #R97 Shotgun
    "gmni_shotgun_ballistic_01_pink_red01":"R97 RedAlert Shotgun",
    "gmni_shotgun_ballistic_01": "R97 Shotgun",
    #P6-LR
    "behr_sniper_ballistic_01":"P6-LR ",
    "behr_sniper_ballistic_01_black01":"P6-LR Black",
    "behr_sniper_ballistic_01_arctic01":"P6-LR Rime",
    #Scalpel Sniper
    "ksar_sniper_ballistic_01":"Scalpel Sniper",
    "ksar_sniper_ballistic_01_white_blue_01":"Scalpel Permafrost Sniper",
    #A03 Rifle
    "gmni_sniper_ballistic_01": "AO3 Rifle",
    "gmni_sniper_ballistic_01_iae2201": "A03 Red Alert Rifle",
    "gmni_sniper_ballistic_01_firerats01": "A03 Scorched Rifle",
    #Grenade Launcher
    "behr_glauncher_ballistic_01": "Grenade Launcher",
    #Ravager Shotgun
    "ksar_shotgun_ballistic_01": "Ravager Shotgun",
    #Custodian SMG
    "ksar_smg_energy_01":"Custodian",
    "ksar_smg_energy_01_black01": "Custodian SMG",
    #Deadrig Shotgun
    "none_shotgun_ballistic_01": "Deadrig shotgun (maybe?)",
    #Tank Weapons
    "HRST_Nova_BallisticCannon_S5":"Kentucky windage",
    "HRST_Storm_LaserRepeater_S3":"Pee Shooter",
    #Special Weapons
    "apar_special_ballistic_01":"Railgun",
    "apar_special_ballistic_02":"Animus Missile Launcher",
}